project:
  type: website
  output-dir: docs

website:
  title: "RoKo-reuther.github.io"
  navbar:
    search: true
    left:
      - text: "Setup and Run"
        file: index.qmd
      - text: "Wang & Van Capellen"
        file: CompVanCap.qmd
      - text: "Interactive std"
        file: interactive_std.qmd
      - text: "Interactive transient"
        file: interactive_transient.qmd
  repo-url: https://github.com/RoKo-reuther/RoKo-reuther.github.io
  repo-actions: [issue]

filters:
  - webr

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: ' '
    code-fold: false
    code-tools: false
    code-link: false
    grid:
      body-width: 1200px
      sidebar-width: 380px
      margin-width: 340px

execute:
  echo: false
  eval: true

bibliography: FeTreatment.bib

