project:
  type: website
  output-dir: docs

website:
  title: "RoKo-reuther.github.io"
  navbar: false

format:
  html:
    theme: flatly
    css: styles.css
    embed-resources: true
    toc: true
    toc-depth: 4
    toc-location: left
    toc-title: ' '
    code-fold: false
    code-tools: false
    grid:
      body-width: 1200px
      sidebar-width: 380px
      margin-width: 340px



